additional_feature_files: None
batch_size: 8
cache_validation_data: false
clip_gradient_norm: 1
data_dir: data/CAMELS_US
dataset: camels_us
device: cuda:0
dynamic_inputs:
- PRCP(mm/day)_nldas_extended
- SRAD(W/m2)_nldas_extended
- Tmax(C)_nldas_extended
- Tmin(C)_nldas_extended
- Vp(Pa)_nldas_extended
- prcp(mm/day)_maurer_extended
- srad(W/m2)_maurer_extended
- tmax(C)_maurer_extended
- tmin(C)_maurer_extended
- vp(Pa)_maurer_extended
- prcp(mm/day)_daymet
- srad(W/m2)_daymet
- tmax(C)_daymet
- tmin(C)_daymet
- vp(Pa)_daymet
dynamics_embedding:
  type: fc
  hiddens:
  - 64
  activation: tanh
  dropout: 0.0
embedding_hiddens: 16
epochs: 30
experiment_name: FullTransformer_batch_size8
forcings:
- nldas_extended
- maurer_extended
- daymet
head: regression
hidden_size: 256
initial_forget_bias: 3
learning_rate:
  0: 0.001
  10: 0.0005
  25: 0.0001
log_interval: 5
log_tensorboard: true
loss: NSE
metrics:
- NSE
- MSE
- RMSE
- KGE
- Alpha-NSE
- Pearson-r
- Beta-NSE
- Peak-Timing
- Missed-Peaks
model: fullTransformer
num_workers: 8
optimizer: Adam
output_dropout: 0.4
predict_last_n: 1
save_validation_results: false
save_weights_every: 1
seq_length: 365
static_attributes:
- elev_mean
- slope_mean
- area_gages2
- frac_forest
- lai_max
- lai_diff
- gvf_max
- gvf_diff
- soil_depth_pelletier
- soil_depth_statsgo
- soil_porosity
- soil_conductivity
- max_water_content
- sand_frac
- silt_frac
- clay_frac
- carbonate_rocks_frac
- geol_permeability
- p_mean
- pet_mean
- aridity
- frac_snow
- high_prec_freq
- high_prec_dur
- low_prec_freq
- low_prec_dur
statics_embedding:
  type: fc
  hiddens:
  - 64
  activation: tanh
  dropout: 0.0
target_variables:
- QObs(mm/d)
test_basin_file: basin_lists/10_basins.txt
test_end_date: 30/09/1999
test_start_date: 01/10/1989
train_basin_file: basin_lists/10_basins.txt
train_end_date: 30/09/2008
train_start_date: 01/10/1999
transformer_dim_feedforward: 128
transformer_dropout: 0
transformer_nheads: 4
transformer_nlayers: 4
transformer_positional_dropout: 0.0
transformer_positional_encoding_type: sum
use_basin_id_encoding: false
validate_every: 5
validate_n_random_basins: 5
validation_basin_file: basin_lists/10_basins.txt
validation_end_date: 30/09/1989
validation_start_date: 01/10/1980
